const bannedWords = [
  "scam",
  "fraud",
  "phishing",
  "fake",
  "spam",
  "lottery",
  "prize",
  "winner",
  "nigerian prince",
  "inheritance",
  "hacker",
  "malware",
  "trojan",
  "virus",
  "ransomware",
  "spyware",
  "identity theft",
  "credit card scam",
  "Ponzi scheme",
  "investment fraud",
  "get rich quick",
  "pyramid scheme",
  "counterfeit",
  "unauthorized",
  "illegal",
  "money laundering",
  "clickbait",
  "adware",
  "deceptive",
  "blackmail",
  "scammer",
  "debt relief scam",
  "job scam",
  "IRS scam",
  "robocall",
  "sextortion",
  "wire fraud",
  "advance fee scam",
  "fake charity",
  "charity fraud",
  "email scam",
  "social security scam",
  "bitcoin scam",
  "crypto fraud",
  "forex scam",
  "fake news",
  "spam message",
  "spam call",
  "spam email",
  "false advertising",
  "adult",
  "porn",
  "xxx",
  "sex",
  "nude",
  "escort",
  "prostitution",
  "incest",
  "rape",
  "abuse",
  "BDSM",
  "fetish",
  "bondage",
  "hentai",
  "camgirl",
  "camwhore",
  "sugar daddy",
  "sugar baby",
  "orgy",
  "gangbang",
  "threesome",
  "erotic",
  "erotica",
  "lust",
  "vibrator",
  "dildo",
  "anal",
  "oral",
  "cum",
  "semen",
  "deepfake",
  "onlyfans",
  "nsfw",
  "leaked",
  "revenge porn",
  "profanity",
  "curse",
  "swear",
  "fuck",
  "shit",
  "bitch",
  "bastard",
  "douche",
  "asshole",
  "cunt",
  "piss",
  "dick",
  "cock",
  "pussy",
  "nigger",
  "chink",
  "fag",
  "retard",
  "spic",
  "gook",
  "whore",
  "slut",
  "tranny",
  "homo",
  "dyke",
  "freak",
  "meaningless",
  "asjdkl",
  "lorem",
  "ipsum",
  "qwerty",
  "zxcasd",
  "blah",
  "blabla",
  "jibberish",
  "gibberish",
  "random text",
  "nonsense",
  "abcdefg",
  "hijklmn",
  "opqrst",
  "uvwxyz",
  "asdfgh",
  "qazwsx",
  "yxcvbn",
  "randomwords",
  "asdasd",
  "skdjfh",
  "qwertyuiop",
  "lkjhgfdsa",
  "poiuytrewq",
  "mnxbcv",
  "qazxsw",
  "poiuyt",
  "zxcvbn",
  "asdfghjkl",
  "lmnopqrs",
  "tuvwxyz",
  "abcdefgh",
  "ijklmnop",
  "qrstuvwx",
  "random123",
  "test123",
  "password123",
  "testtest",
  "hello123",
  "admin123",
  "user123",
  "letmein",
  "welcome1",
  "iloveyou",
  "sunshine",
  "password1",
  "football1",
  "baseball1",
  "dragon1",
  "monkey1",
  "princess1",
  "qwerty1",
  "login1",
  "12345678",
  "87654321",
  "abc12345",
  "54321abc",
  "p@ssw0rd",
  "pa$$word",
  "testword",
  "simpleword",
  "badpassword",
  "badwords",
  "badwordslist",
  "expletives",
  "swearwords",
  "offensive",
  "inappropriate",
  "derogatory",
  "racist",
  "hateful",
  "discriminatory",
  "slur",
  "ethnic slur",
  "homophobic slur",
  "transphobic slur",
  "offensive term",
  "bad term",
  "explicit content",
  "nsfw content",
  "sensitive content",
  "inappropriate language",
  "censored words",
  "restricted words",
  "forbidden words",
  "banned words",
  "blacklisted words",
  "adult language",
  "sexually explicit",
  "not safe for work",
  "prohibited words",
  "not allowed words",
  "vulgar language",
  "obscene language",
  "profane words",
  "curse words",
  "insults",
  "slang words",
  "taboo words",
  "off-limits words",
  "restricted content",
  "censored content",
  "prohibited content",
  "flagged words",
  "hate speech",
  "derogatory language",
  "demeaning words",
  "hurtful words",
  "toxic words",
  "violent words",
  "trigger words",
  "words to avoid",
  "unsuitable words",
  "dangerous words",
  "harmful words",
  "offensive speech",
  "unacceptable words",
  "off-limits speech",
  "inappropriate speech",
  "rude words",
  "disrespectful words",
  "insulting words",
  "hurtful speech",
  "unprofessional words",
  "negative words",
  "dark words",
  "sensitive words",
  "not good words",
  "unwanted words",
  "filtered words",
  "restricted speech",
  "banned speech",
  "taboo speech",
  "unethical words",
  "morally wrong words",
  "unsuitable speech",
  "unwelcome words",
  "malicious words",
  "evil words",
  "aggressive words",
  "demeaning speech",
  "disparaging words",
  "horrible words",
  "hateful terms",
  "bad slang",
  "disgusting words",
  "triggering words",
  "unpleasant words",
  "off-putting words",
  "cringe words",
  "painful words",
  "mentally harmful words",
  "emotionally harmful words",
  "discrediting words",
  "unfriendly words",
  "unfair words",
  "unjust words",
  "biased words",
  "politically incorrect words",
  "problematic words",
  "malign words",
  "slanderous words",
  "damaging words",
  "offense-causing words",
  "publicly inappropriate words",
  "morally offensive words",
  "ethically offensive words",
  "criminal words",
  "dangerous speech",
  "manipulative words",
  "coercive words",
  "deceptive speech",
  "brainwashing words",
  "gaslighting words",
  "misleading words",
  "threatening words",
  "harassing words",
  "intimidating words",
  "violent speech",
  "unethical speech",
  "immoral words",
  "immoral speech",
];

export default bannedWords;
